export const Strings = {
  app: {
    name: 'Noto',
    tagline: 'Think clearly. Write freely.',
    version: '1.0.0',
  },

  auth: {
    login: 'Sign In',
    logout: 'Sign Out',
    email: 'Email address',
    password: 'Password',
    emailPlaceholder: 'you@example.com',
    passwordPlaceholder: '••••••••',
    forgotPassword: 'Forgot password?',
    loginSubtitle: 'Welcome back to Noto',
    loginTitle: 'Sign in',
    noAccount: "Don't have an account?",
    orContinueWith: 'or continue with',
    verificationTitle: 'Verify your identity',
    verificationSubtitle: 'Enter the 6-digit code sent to your email',
    resendCode: 'Resend code',
    verify: 'Verify',
    signupTitle: 'Create account',
    signupSubtitle: 'Join us today',
    userName: 'Username',
    userNamePlaceholder: 'your_username',
    confirmPassword: 'Confirm password',
    confirmPasswordPlaceholder: '••••••••',
    signUp: 'Create account',
    alreadyHaveAccount: 'Already have an account?',
    signupSuccess: 'Account created successfully!',
    loginSuccess: 'Login successful!',
  },

  notes: {
    title: 'My Notes',
    newNote: 'New Note',
    editNote: 'Edit Note',
    deleteNote: 'Delete Note',
    noNotes: 'No notes yet',
    noNotesSubtitle: 'Tap + to capture your first thought',
    titlePlaceholder: 'Note title...',
    contentPlaceholder: 'Start writing...',
    save: 'Save Note',
    update: 'Update Note',
    delete: 'Delete',
    cancel: 'Cancel',
    confirmDelete: 'Delete this note?',
    confirmDeleteSubtitle: 'This action cannot be undone.',
    lastEdited: 'Last edited',
    characters: 'characters',
    words: 'words',
  },

  ai: {
    explain: 'Explain',
    summarize: 'Summarize',
    aiActions: 'AI Tools',
    aiActionsSubtitle: 'Choose what you want to do',
    explaining: 'Generating explanation...',
    summarizing: 'Generating summary...',
    aiExplain: 'AI Explain',
    aiSummarize: 'AI Summary',
    simpleMode: 'Simple',
    technicalMode: 'Technical',
    simpleExplanation: 'Simple Explanation',
    technicalExplanation: 'Technical Explanation',
    aiSubtitle: 'Powered by local AI',
    copyExplanation: 'Copy',
    copied: 'Copied!',
    tryAgain: 'Try again',
    errorExplaining: 'Could not generate explanation. Please try again.',
    errorSummarizing: 'Could not generate summary. Please try again.',
  },

  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'No internet connection. Check your network.',
    unauthorized: 'Session expired. Please sign in again.',
    invalidCredentials: 'Invalid email or password.',
    emailRequired: 'Email is required.',
    emailInvalid: 'Enter a valid email address.',
    passwordRequired: 'Password is required.',
    passwordMinLength: 'Password must be at least 8 characters.',
    noteTitle: 'Note title is required.',
    noteContent: 'Note content cannot be empty.',
    userNameRequired: 'Username is required',
    confirmPasswordRequired: 'Please confirm your password',
    passwordMismatch: 'Passwords do not match',
    emailAlreadyExists: 'An account with this email already exists',
  },

  common: {
    loading: 'Loading...',
    retry: 'Retry',
    done: 'Done',
    back: 'Back',
    search: 'Search notes...',
    settings: 'Settings',
    profile: 'Profile',
    ok: 'OK',
    yes: 'Yes',
    no: 'No',
  },
} as const;

export default Strings;
